language: python

# Run jobs on container-based infrastructure, can be overridden per job

matrix:
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    - os: osx
      language: generic
      env: PYTHON_VER=3.6
#    - os: osx
#      language: generic
#      env: PYTHON_VER=3.7

    - os: linux
      python: 3.6
      env: PYTHON_VER=3.6
#    - os: linux
#      dist: xenial
#      python: 3.7
#      env: PYTHON_VER=3.7

before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:

    # Create test environment for package
  - python devtools/scripts/create_conda_env.py -n=paprika-dev -p=$PYTHON_VER devtools/conda-envs/test_env.yaml
    # Activate the test environment
  - conda activate paprika-dev
    # Build and install package
  - python setup.py develop --no-deps


script:
  - pytest -v --cov=paprika paprika/tests/

notifications:
    email: false

after_success:
  - codecov
