name: paprika

channels:
  - conda-forge
  - omnia
dependencies:
  
  # Base depends
  - python ==3.7
  - setuptools

  # Sphinx specific
  - numpydoc
  - sphinx
  - nbsphinx
  - m2r >=0.2.1
  - sphinx_rtd_theme

  - pip
  - numpy
  - scipy
  - parmed
  - mdtraj
  - pymbar
  - openmm
