name: paprika

channels:
  - conda-forge

dependencies:
    # Base depends
    - python ==3.8
    - setuptools

    # Sphinx specific
    - nbsphinx
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex
    - numpydoc
    - pandoc
    - ipython

    # Standard dependencies
    - numpy
    - pandas
    - lxml
    - icu 58*  # REQUIRED - DO NOT REMOVE.
    - networkx

