name: paprika

channels:
  - conda-forge
  - omnia

dependencies:
  # Base depends
  - python ==3.7
  - setuptools

  # Sphinx specific
  - numpydoc
  - pandoc
  - sphinx
  - nbsphinx
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex ==1.0.0

  # Standard dependencies
  - pip
  - numpy
  - scipy
  - parmed
  - mdtraj
  - pymbar
  - openmm
