name: paprika

channels:
  - conda-forge

dependencies:
  # Base depends
  - python ==3.7
  - setuptools

  # Sphinx specific
  - nbsphinx
  - sphinx
  - sphinx_rtd_theme
  - numpydoc

  # Standard dependencies
  - pip
  - numpy
  - scipy
  - parmed
  - mdtraj
